### ISSUE TITLE
The procedure entry point GetTickCount64 could not be located in the dynamic link library KERNEL32.dll

### ISSUE THREAD

**Issue by donho** [donho/notepad-plus-plus#102]
WinGup (compiled by VS 2013) get the following message under XP:
"The procedure entry point GetTickCount64 could not be located in the dynamic link library KERNEL32.dll"

Any idea to avoid this issue?

**Comment by pnedev** [comment]
According to MSDN GetTickCount64 is supported from Vista onward (that excludes XP I think).
Can't we use GetTickCount? It's counter is DWORD size  = 49.7 days since the system started.
I haven't checked what you are using GetTickCount64 for so I'm not sure GetTickCount is a viable replacement.

**Comment by donho** [comment]
Thank you @pnedev, this issue has been solved by setting xptool in vs2013. However there is another issue about winssl layer obsolet problem. I'm working on it.
