### ISSUE TITLE
Can we compile it on unix and Linux, Mac OS X?

### ISSUE THREAD

**Issue by liuxuan30** [donho/notepad-plus-plus#108]
Can we compile it on unix and Linux, Mac OS X? Whatever the compiler the OS has

**Comment by andreas-jonsson** [comment]
Compile: probably not without a lot of work since it has been written with Windows in mind.
Run: possibly, try WINE on Linux (http://bur.st/~gunny/winehowto.html) and similar solutions on other platforms (if they exist).

**Comment by liuxuan30** [comment]
Seems it has used many windows APIs probably... such a pity it is only on windows:(

**Comment by ariccio** [comment]
Notepad++ is Windows only, but [the core text-editing functionality](http://www.scintilla.org/index.html) is NOT.

**Comment by marcows** [comment]
@liuxuan30 I was not sure whether you meant compiling on Linux **for** Windows or on Linux **for** Linux. I fixed the first case, see issue #385

**Comment by liuxuan30** [comment]
@marcows just want to install notepad++ on Mac

**Comment by milipili** [comment]
https://www.youtube.com/watch?v=k0nKurJKNbM

**Comment by carlitossanchez** [comment]
yeah, please i a windows mac and linux user and i hate (and many other people too) the others editing text programs, so, i know its very difficult to do a MAC version, but we really really need one, with the winbottler its terrible works, and i hate the sublime text alternative....

Please when you have a little time do a OS X version

thanks a lot
