### ISSUE TITLE
CheckSingleFile Failed!!

### ISSUE THREAD

**Issue by hardyc3** [donho/notepad-plus-plus#19]
![2015-05-04_0943](https://cloud.githubusercontent.com/assets/2830502/7456491/1499b950-f242-11e4-99f3-79b9534f1269.png)
![2015-05-04_0945](https://cloud.githubusercontent.com/assets/2830502/7456533/59873c90-f242-11e4-9257-d3bce8b6cc9b.png)

I get the above two error dialogs when opening multiple files. It seems like it might have something to do with the number of directories and the length of the file name because I couldn't reproduce it with two short file names from somewhere like my desktop folder. 
See the images for example directory structures and file names that cause the problem.

I should mention this only started after the most recent update I ran. Before then I never got this error and I've been opening multiple files from a directory structure like the above for years.

Just found that this is a duplicate of several issues already listed on source forge.

**Comment by hardyc3** [comment]
I should mention this only started after the most recent update I ran. Before then I never got this error and I've been opening multiple files from a directory structure like the above for years.

**Comment by hardyc3** [comment]
Looking through the issue in source forge it looks like this has already been addressed.

**Comment by ariccio** [comment]
[I submitted a patch for it yesterday](https://github.com/donho/notepad-plus-plus/pull/15) but it hasn't been merged yet.
