### ISSUE TITLE
"checkSingleFile failed!" - "the buffer passed to GetFullPathName was too small!"

### ISSUE THREAD

**Issue by gdwhite** [donho/notepad-plus-plus#25]
I get the following error dialog when I double-click a single file in explorer:  

"checkSingleFile failed!" - "the buffer passed to GetFullPathName was too small!"
![notepad errors - 1](https://cloud.githubusercontent.com/assets/2054830/7471046/518ddb62-f2f0-11e4-912c-cf8ea2934065.png)

When I click "OK" I then get another error dialog:

"path that failed:" (shows path of file that was clicked)
![notepad errors - 2](https://cloud.githubusercontent.com/assets/2054830/7471047/518f5028-f2f0-11e4-99ec-346b0681a9ce.png)

The funny thing is that it works without error when I left-click that same file and choose "Edit with Notepad++".

I eventually nailed it down to the path exceeding a certain length (>=165) in a certain directory via a process of elimination.  The original file that caused the error is:
***"C:\Users\Gary\Music\Fleetwood Mac\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam stereo-M1-SBD.txt"***

The error occurs with the following file (pathname length == 165):
***"C:\Users\Gary\Music\Fleetwood Mac\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam stereo-M1-SB.txt"***

but not with this one (pathname length == 164):
***"C:\Users\Gary\Music\Fleetwood Mac\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam stereo-M1-S.txt"***

I tried various combinations of filenames/lengths in "C:\Users\Gary\Music\some random directory with a really long path\" but couldn't get the problem to occur even with the pathname length >=165.  I then tried the following 2 files with more generic filenames in the original directory:
***"C:\Users\Gary\Music\Fleetwood Mac\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx164.txt"
"C:\Users\Gary\Music\Fleetwood Mac\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx165.txt"***

The error occurred with the second file but not with the first.

Here's my system/version info:
*Notepadd++ v6.7.7
Windows 8.1 64 bit (fully patched)*

**Comment by ariccio** [comment]
This issue (#19) is a known issue.

See https://github.com/donho/notepad-plus-plus/issues/19 for the GitHub issue
See https://sourceforge.net/p/notepad-plus/bugs/5266/ for the SourceForge issue
See https://github.com/donho/notepad-plus-plus/pull/15 for the patch that fixes it.

**Comment by ariccio** [comment]
Please close as a duplicate?

**Comment by gdwhite** [comment]
Hi Alexander,

I'm just reading through the various links that you posted to determine if this is the same error I'm getting and, if so, where the appropriate patch is and how to apply it.  The issues that you referenced (i.e. Github #19 and SF #5266 both indicate that this is a problem with opening multiple files which is not where I'm encountering the problem (it happens when I double-click a single file).  This may well be the same issue but I wasn't sure if you had just done a quick cursory reading of my problem description and missed the difference.

I also was trying to grok the steps (rebuild everything or just patch current install?) and file(s) needed to fix it (if this is the same issue).  Github #15 is a source file which leads me to believe that s full rebuild is necessary whereas SF #5266 references patch 656 (which seems to introduce a bug that #15 is meant to fix?); I didn't see a patch newer than 656 that seemed to address the bug so it looks like a patch isn't on the menu.

Anyway, if you can confirm that this issue is one and the same I will be happy to close this out.

Thanks for your work on the project!
Gary

**Comment by ariccio** [comment]
mm. Sorry, looks like I jumped to judgement here, (*major duh*) and assumed that was *several* paths. It's just one *really* long path. I take back what I said: "Please close as a duplicate?".

Lemme see if I understand what's going on.

**Comment by ariccio** [comment]
Is Notepad++ **already** open, when you try to open the problematic file?

What's really weird, is that the problematic file's path shouldn't be long enough to cause this problem in the first place. 

The size of the buffer passed to [`::GetFullPathName`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364963) is `MAX_PATH` (260 characters) - which is more than the 165 character path that's causing the problem: `"C:\Users\Gary\Music\Fleetwood Mac\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam stereo-M1-SBD.txt"`

As a side note: Notepad++, like ***many*** other Windows applications, misinterprets `MAX_PATH` as "**the** length of the longest possible path", which WAS true, 25 years ago. In fact, `MAX_PATH` means "the maximum length of *a single path component*" - i.e. the *name* of a file/folder.

For paths LONGER than `MAX_PATH`, my patch is a partial fix that is intended to preserve the current Notepad++ behavior, which - this issue notwithstanding - is very much so broken. 


If you have a copy of Python installed, could you try running something like this:

```
>>>import os
>>>os.path.abspath("C:\\Users\\Gary\\Music\\Fleetwood Mac\\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam\\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam stereo-M1-SBD.txt")
```
...and report the results?

**Comment by gdwhite** [comment]
It happens whether or not NP++ is already open.

Here's the Python results:
```
>>> import os
>>> os.path.abspath("C:\\Users\\Gary\\Music\\Fleetwood Mac\\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam\\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam stereo-M1-SBD.txt")
'C:\\Users\\Gary\\Music\\Fleetwood Mac\\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam\\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam stereo-M1-SBD.txt'
>>> 
```

As noted in my original post, it's not just the length that's causing the problem; the following file opens with no errors in spite of having the same path length as the offending files in the original directory:

`C:\Users\Gary\Music\some random directory with a really long path\Fleetwood Mac Clapton 1970-02-05 BostonMA Tea Party Jam stereo-M1-Sxxxxxxxxxxxxxxxxxxxxxxxxx165.txt`

Are you unable to replicate the error?

**Comment by ariccio** [comment]
> Are you unable to replicate the error?

In a **very** quick attempt, I could not. But I plan to create `"Fleetwood Mac\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam stereo-M1-SBD.txt"` in my `Music` folder; which will hopefully replicate the issue.

**Comment by ariccio** [comment]
I managed to replicate it.

When I doubled the size of the buffer passed to checkSingleFile, it returned this:

```
L"C:\\Users\\Alexander Riccio\\Documents\\GitHub\\notepad-plus-plus\\PowerEditor\\visual.net\\\"C:\\Users\\Alexander Riccio\\Music\\Fleetwood Mac\\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam\\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam stereo-M1-S.txt\""
```

....which is really weird.

**Comment by ariccio** [comment]
What's really *really* weird, is that when I pass it to the test program that I wrote for that patch, I get this:

```
argc: 2
argv[ 2 ]: `C:\Users\Alexander Riccio\Documents\Visual Studio 2013\Projects\test_GetFullPathName_single_file\Debug\test_GetFullPathName_single_file.exe`
argv[ 2 ]: `C:\Users\Alexander Riccio\Music\Fleetwood Mac\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam stereo-M1-S.txt`


multiplePaths: `C:\Users\Alexander Riccio\Music\Fleetwood Mac\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam stereo-M1-S.txt`


Length of input to GetFullPathName: 179


        multiplePaths: `C:\Users\Alexander Riccio\Music\Fleetwood Mac\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam stereo-M1-S.txt`

        result: 179

        resulting buffer: `C:\Users\Alexander Riccio\Music\Fleetwood Mac\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam\Fleetwood Mac & Clapton 1970-02-05 Boston,MA Tea Party Jam stereo-M1-S.txt`
```

Notice that the buffer returned by ::GetFullPathName in Notepad++ has the path to the current working directory prepended, which thus means that the buffer is too small....but why would it prepend the current working directory??

**Comment by ariccio** [comment]
....no I know **that**, but I'd like to get to the bottom of ::GetFullPathName's bad behavior
