### ISSUE TITLE
update fails because of https

### ISSUE THREAD

**Issue by egoroof** [donho/notepad-plus-plus#43]
I found that site is opened only by https. And notepad 6.7.7 shows this error when I try to update:

![1](https://cloud.githubusercontent.com/assets/2605831/7548855/ef8c0602-f64e-11e4-9944-0ce04c13dd88.png)

I use win8.1x64

**Comment by milipili** [comment]
The permanent redirect to https has been temporary disabled.

**Comment by egoroof** [comment]
Good. Now it's ok.
The next step is to enable https in libcurl?

**Comment by milipili** [comment]
Probably. Anyway, SSL termination proxy would require more fine grained configuration to allow the update of older versions via https.

**Comment by donho** [comment]
curl lib used in WinGup doesn't support SSL. 
I'll make WinGup supports SSL ASAP.
The new WinGup will be included in the next Notepad++ release.

**Comment by milipili** [comment]
The permanent redirect is active again. Do not hesitate to report any problem.

**Comment by donho** [comment]
@milipili Awesome! Thank you!

**Comment by AlbertoP64** [comment]
Hi @milipili @egoroof , currently receiving this same message and error trying to update from 7.2. Is this discussion to be reopened? And please, what is the cause behind this error? I don't understand from the above messages, what the real problem behind the messages is. Thanks and regards.
