### ISSUE TITLE
checkSingleFile failed!!

### ISSUE THREAD

**Issue by daekin** [donho/notepad-plus-plus#69]
When using context menu extension to open multiple files in Notepad++ I get this error message:

checkSingleFile failed!!
the buffer passed to GetFullPathName was too small!

However, all files are opened correctly afterwards.

System information: Windows 8.1 x64, Notepad++ 6.7.7

**Comment by ariccio** [comment]
This issue has been reported *ad nauseam*. It was my fault, its been fixed.

**Comment by daekin** [comment]
OK, I will confirm if it has been fixed once 6.7.8 is officially released.

**Comment by ariccio** [comment]
As of 5c272a88184748435acce70bceca5ae33f989731, I believe that release is imminent.

**Comment by daekin** [comment]
After installing Notepad++ 6.7.8 I can confirm that this bug was indeed fixed.
